import snapshot from './generated/github.json'

export interface GitHubCommit {
  repo: string
  sha: string
  message: string
  date: string
  url: string
}

export interface GitHubSnapshot {
  syncedAt: string
  profile: {
    login: string
    url: string
    avatarUrl: string
    publicRepos: number
    followers: number
    memberSince: string
  }
  languagesByYear: { year: number; languages: { name: string; repos: number }[] }[]
  recentCommits: GitHubCommit[]
}

/** Generated by scripts/sync-github.mjs before every build. */
export const github: GitHubSnapshot = snapshot
